spring:
  profiles:
    active: local
  application:
    name: ai-no-code-generator-backend
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ai_no_code_generator
    username: root
    password: 123456

server:
  port: 8123
  servlet:
    context-path: /api

